# Generated by Django 3.1 on 2022-11-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadduty', '0002_auto_20221120_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
