# Generated by Django 3.1 on 2022-11-20 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadduty', '0003_asd'),
    ]

    operations = [
        migrations.AddField(
            model_name='asd',
            name='challan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roadduty.challan'),
        ),
    ]
