# Generated by Django 3.1 on 2022-11-26 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadduty', '0005_auto_20221120_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='challanimage',
            name='type',
            field=models.CharField(choices=[('whole', 'whole'), ('cutout', 'cutout'), ('bulk', 'bulk')], default='bulk', max_length=50),
        ),
        migrations.AlterField(
            model_name='challan',
            name='amount',
            field=models.IntegerField(blank=True, default=2000),
        ),
        migrations.AlterField(
            model_name='challan',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='challan',
            name='status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('to_check_manually', 'to_check_manually'), ('query_raised', 'query_raised'), ('paid', 'paid')], default='unpaid', max_length=50),
        ),
    ]
