# Generated by Django 3.1 on 2022-11-26 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadduty', '0007_auto_20221126_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challan',
            old_name='locations',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='challan',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
