# Generated by Django 3.1 on 2022-11-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadduty', '0008_auto_20221126_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='rider',
            name='license_number',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
