# Generated by Django 3.1 on 2022-11-28 18:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadduty', '0009_auto_20221126_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='challan',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roadduty.rider'),
        ),
        migrations.AlterField(
            model_name='challan',
            name='status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('to_check_manually', 'to_check_manually'), ('query_raised', 'query_raised'), ('invalid', 'invalid'), ('paid', 'paid')], default='unpaid', max_length=50),
        ),
    ]
