# Generated by Django 3.1 on 2022-11-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadduty', '0010_auto_20221129_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
