# Generated by Django 3.1 on 2022-11-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadduty', '0004_asd_challan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ASD',
            new_name='ChallanImage',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
